# Site settings
title: Credify Tech
email: dev@credify.one
description: > # this means to ignore newlines until "url:"
  Credify's Engineering team builds an embedded finance platform in Southeast Asia.
url: https://vn.engineering.credify.one # the base hostname & protocol for your site

social_media:
  facebook: credify.one
  github: credify-pte-ltd
  twitter: CredifyOne
  linkedin: credifyone

disqus:
  shortname: credify-pte-ltd

google_analytics_id: G-9JZVXSGJL7

# Post settings
post:
  date_format: '%-d %b %Y'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title
paginate: 8
paginate_path: "/blog/:num/"
encoding: UTF-8
gems: ['jekyll-paginate', 'jekyll-archives']

jekyll-archives:
  enabled: ['categories']
  layout: 'archive'
  permalinks:
    category: '/categories/:name/'

# Custom headers
webrick:
  headers:
    Content-Security-Policy: frame-ancestors 'none';
    X-Frame-Options: DENY
